In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
customers = pd.read_csv("C:/Users/hp/Desktop/customer-churn-analysis-python-/data/raw_data/customers.csv")
customers.shape
customers.head()
customers.info()
customers.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       15000 non-null  int64
 1   customer_name     15000 non-null  object
 2   gender            15000 non-null  object
 3   age               15000 non-null  int64
 4   city              14700 non-null  object
 5   state             15000 non-null  object
 6   join_date         15000 non-null  object
 7   plan_id           15000 non-null  int64
 8   contract_type     15000 non-null  object
 9   internet_service  13309 non-null  object
 10  tenure_months     15000 non-null  int64
 11  churn             15000 non-null  object
dtypes: int64(4), object(8)
memory usage: 1.4+ MB

        customer_id           age       plan_id  tenure_months
count  15000.000000  15000.000000  15000.000000   15000.000000
mean    7500.500000     43.434133      2.494933      30.431867
std     4330.271354     15.057542      1.117105      17.206720
min        1.000000     18.000000      1.000000       1.000000
25%     3750.750000     31.000000      1.000000      16.000000
50%     7500.500000     43.000000      2.000000      30.000000
75%    11250.250000     57.000000      3.000000      45.000000
max    15000.000000     69.000000      4.000000      60.000000

In [3]:
customers.isnull().sum()

customer_id            0
customer_name          0
gender                 0
age                    0
city                 300
state                  0
join_date              0
plan_id                0
contract_type          0
internet_service    1691
tenure_months          0
churn                  0
dtype: int64

In [4]:
customers.duplicated().sum()

np.int64(0)

In [5]:
customers.nunique()

customer_id         15000
customer_name       14577
gender                  2
age                    52
city                  316
state                   7
join_date            1600
plan_id                 4
contract_type           3
internet_service        3
tenure_months          60
churn                   2
dtype: int64

In [6]:
customers.describe(include="object")

,customer_name,gender,city,state,join_date,contract_type,internet_service,churn
count,15000,15000,14700,15000,15000,15000,13309,15000
unique,14577,2,316,7,1600,3,3,2
top,Anita Gala,Male,Ghaziabad,Gujarat,2021-12-16,Monthly,Fiber,No
freq,3,7521,94,2279,21,7508,5837,11466

In [19]:
customers.columns

Index(['customer_id', 'customer_name', 'gender', 'age', 'city', 'state',
       'join_date', 'plan_id', 'contract_type', 'internet_service',
       'tenure_months', 'churn'],
      dtype='object')

In [7]:
plans = pd.read_csv("C:/Users/hp/Desktop/customer-churn-analysis-python-/data/raw_data/plans.csv")
plans.shape
plans.head()
plans.info()
plans.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   plan_id      4 non-null      int64
 1   plan_name    4 non-null      object
 2   monthly_fee  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

        plan_id  monthly_fee
count  4.000000     4.000000
mean   2.500000   699.000000
std    1.290994   391.578004
min    1.000000   299.000000
25%    1.750000   449.000000
50%    2.500000   649.000000
75%    3.250000   899.000000
max    4.000000  1199.000000

In [8]:
plans.isnull().sum()

plan_id        0
plan_name      0
monthly_fee    0
dtype: int64

In [9]:
plans.nunique()

plan_id        4
plan_name      4
monthly_fee    4
dtype: int64

In [10]:
plans.duplicated().sum()

np.int64(0)

In [16]:
plans.describe(include="object")

       plan_name
count          4
unique         4
top        Basic
freq           1

In [21]:
plans.columns

Index(['plan_id', 'plan_name', 'monthly_fee'], dtype='object')

In [11]:
customer_usage = pd.read_csv("C:/Users/hp/Desktop/customer-churn-analysis-python-/data/raw_data/customer_usage.csv")
customer_usage.shape
customer_usage.head()
customer_usage.info()
customer_usage.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   usage_id       45000 non-null  int64
 1   customer_id    45000 non-null  int64
 2   month          45000 non-null  object
 3   data_usage_gb  45000 non-null  float64
 4   call_minutes   45000 non-null  int64
 5   sms_count      45000 non-null  int64
dtypes: float64(1), int64(4), object(1)
memory usage: 2.1+ MB

           usage_id   customer_id  data_usage_gb  call_minutes     sms_count
count  45000.000000  45000.000000   45000.000000  45000.000000  45000.000000
mean   22500.500000   7508.383689     251.475980   2009.022644    249.115378
std    12990.525394   4329.147277     143.903597   1148.569007    144.354629
min        1.000000      1.000000       1.010000     20.000000      0.000000
25%    11250.750000   3776.750000     126.362500   1018.000000    125.000000
50%    22500.500000   7527.500000     252.920000   2007.000000    249.000000
75%    33750.250000  11265.000000     375.360000   3009.000000    374.000000
max    45000.000000  15000.000000     499.990000   3999.000000    499.000000

In [12]:
customer_usage.isnull().sum()

usage_id         0
customer_id      0
month            0
data_usage_gb    0
call_minutes     0
sms_count        0
dtype: int64

In [13]:
customer_usage.duplicated().sum()

np.int64(0)

In [14]:
customer_usage.nunique()

usage_id         45000
customer_id      14240
month              365
data_usage_gb    29619
call_minutes      3980
sms_count          500
dtype: int64

In [18]:
customer_usage.describe(include="object")

             month
count        45000
unique         365
top     2024-10-31
freq           152

In [15]:
customer_usage

,usage_id,customer_id,month,data_usage_gb,call_minutes,sms_count
0,1,11659,2024-05-17,370.63,3655,117
1,2,9850,2024-11-17,303.87,1629,325
2,3,2878,2024-05-13,261.17,3046,182
3,4,12507,2024-03-19,188.82,462,433
4,5,11516,2024-02-04,218.29,3818,287
...,...,...,...,...,...,...
44995,44996,9432,2024-12-15,381.69,2311,472
44996,44997,12251,2024-12-05,263.20,1521,131
44997,44998,870,2024-10-26,216.05,2421,307
44998,44999,1861,2024-01-05,331.16,3549,199
44999,45000,10286,2024-09-18,467.53,91,35

In [23]:
customer_usage.columns

Index(['usage_id', 'customer_id', 'month', 'data_usage_gb', 'call_minutes',
       'sms_count'],
      dtype='object')

## Initial Data Inspection Observations
- Successfully imported all datasets.
- Verified the dimensions of each table.
- Checked data types and identified categorical and numerical columns.
- Examined missing values and duplicate records.
- Reviewed descriptive statistics.
- Confirmed primary keys and common columns for future joins.
- No data cleaning has been performed in this notebook.