In [1]:
import pandas as pd
import numpy as np

In [2]:
customers = pd.read_csv("C:/Users/hp/Desktop/customer-churn-analysis-python-/data/raw_data/customers.csv")

## CHECK DUPLICATES

In [3]:
customers.duplicated().sum()

np.int64(0)

In [4]:
plans = pd.read_csv("C:/Users/hp/Desktop/customer-churn-analysis-python-/data/raw_data/plans.csv")

In [5]:
plans.duplicated().sum()

np.int64(0)

In [6]:
customer_usage = pd.read_csv("C:/Users/hp/Desktop/customer-churn-analysis-python-/data/raw_data/customer_usage.csv")

In [7]:
customer_usage.duplicated().sum()

np.int64(0)

In [8]:
support_tickets = pd.read_csv("C:/Users/hp/Desktop/customer-churn-analysis-python-/data/raw_data/support_tickets.csv")

In [9]:
support_tickets.duplicated().sum()

np.int64(0)

In [10]:
transactions = pd.read_csv("C:/Users/hp/Desktop/customer-churn-analysis-python-/data/raw_data/transactions.csv")

In [11]:
transactions.duplicated().sum()

np.int64(0)

## CHECK DUPLICATES ID'S

In [12]:
customers["customer_id"].duplicated().sum()

np.int64(0)

In [13]:
plans["plan_id"].duplicated().sum()

np.int64(0)

In [14]:
transactions["transaction_id"].duplicated().sum()

np.int64(0)

In [15]:
support_tickets["ticket_id"].duplicated().sum()

np.int64(0)

In [16]:
customer_usage["usage_id"].duplicated().sum()

np.int64(0)

## MISSING VALUES

In [17]:
customers.isnull().sum()

customer_id            0
customer_name          0
gender                 0
age                    0
city                 300
state                  0
join_date              0
plan_id                0
contract_type          0
internet_service    1691
tenure_months          0
churn                  0
dtype: int64

In [61]:
customers["internet_service"].value_counts(dropna=False)

internet_service
Fiber    5837
DSL      4440
5G       3032
NaN      1691
Name: count, dtype: int64

In [62]:
customers.groupby(customers["internet_service"].isna())["churn"].value_counts(normalize=True)*100

internet_service  churn
False             No       76.527162
                  Yes      23.472838
True              No       75.753992
                  Yes      24.246008
Name: proportion, dtype: float64

In [64]:
customers["internet_service"]=customers["internet_service"].fillna("Unknown")

In [66]:
customers["internet_service"].value_counts()

internet_service
Fiber      5837
DSL        4440
5G         3032
Unknown    1691
Name: count, dtype: int64

In [68]:
customers["internet_service"].isnull().sum()

np.int64(0)

In [54]:
customers["city"].mode()

0    Ghaziabad
Name: city, dtype: object

In [56]:
customers["city"]=customers["city"].fillna(customers["city"].mode()[0])

In [58]:
customers["city"].isnull().sum()

np.int64(0)

In [60]:
customers["city"].value_counts().head()

city
Ghaziabad     394
Aurangabad     84
Junagadh       69
Durgapur       65
Guntur         64
Name: count, dtype: int64

In [18]:
plans.isnull().sum()

plan_id        0
plan_name      0
monthly_fee    0
dtype: int64

In [19]:
transactions.isnull().sum()

transaction_id    0
customer_id       0
payment_date      0
amount            0
payment_method    0
payment_status    0
dtype: int64

In [20]:
support_tickets.isnull().sum()

ticket_id             0
customer_id           0
issue_type            0
priority              0
resolution_days       0
satisfaction_score    0
dtype: int64

In [21]:
customer_usage.isnull().sum()

usage_id         0
customer_id      0
month            0
data_usage_gb    0
call_minutes     0
sms_count        0
dtype: int64

## CALCULATE MISSING PERCENTAGE

In [22]:
round(customers.isnull().mean()*100,2)

customer_id          0.00
customer_name        0.00
gender               0.00
age                  0.00
city                 2.00
state                0.00
join_date            0.00
plan_id              0.00
contract_type        0.00
internet_service    11.27
tenure_months        0.00
churn                0.00
dtype: float64

## CHECK DATA TYPES

In [23]:
customers.dtypes

customer_id          int64
customer_name       object
gender              object
age                  int64
city                object
state               object
join_date           object
plan_id              int64
contract_type       object
internet_service    object
tenure_months        int64
churn               object
dtype: object

In [24]:
customers["join_date"].dtypes

dtype('O')

In [25]:
transactions.dtypes

transaction_id     int64
customer_id        int64
payment_date      object
amount             int64
payment_method    object
payment_status    object
dtype: object

In [26]:
transactions["payment_date"].dtypes

dtype('O')

In [27]:
customer_usage.dtypes

usage_id           int64
customer_id        int64
month             object
data_usage_gb    float64
call_minutes       int64
sms_count          int64
dtype: object

In [28]:
customer_usage["month"].dtypes

dtype('O')

## CONVERT DATE COLUMNS

In [29]:
customers["join_date"] = pd.to_datetime(customers["join_date"])

In [30]:
transactions["payment_date"] = pd.to_datetime(transactions["payment_date"])

In [31]:
customer_usage["month"] = pd.to_datetime(customer_usage["month"])

In [32]:
customers.dtypes

customer_id                  int64
customer_name               object
gender                      object
age                          int64
city                        object
state                       object
join_date           datetime64[ns]
plan_id                      int64
contract_type               object
internet_service            object
tenure_months                int64
churn                       object
dtype: object

In [33]:
transactions.dtypes

transaction_id             int64
customer_id                int64
payment_date      datetime64[ns]
amount                     int64
payment_method            object
payment_status            object
dtype: object

In [34]:
customer_usage.dtypes

usage_id                  int64
customer_id               int64
month            datetime64[ns]
data_usage_gb           float64
call_minutes              int64
sms_count                 int64
dtype: object

## CHECK CATEGORICAL VALUES

In [35]:
customers["gender"].value_counts(dropna=False)

gender
Male      7521
Female    7479
Name: count, dtype: int64

In [36]:
customers["state"].value_counts(dropna=False)

state
Gujarat           2279
Tamil Nadu        2180
Rajasthan         2175
Karnataka         2119
Delhi             2088
Madhya Pradesh    2081
Maharashtra       2078
Name: count, dtype: int64

In [37]:
customers["contract_type"].value_counts(dropna=False)

contract_type
Monthly     7508
Annual      4517
Two-Year    2975
Name: count, dtype: int64

In [38]:
customers["internet_service"].value_counts(dropna=False)

internet_service
Fiber    5837
DSL      4440
5G       3032
NaN      1691
Name: count, dtype: int64

In [39]:
customers["churn"].value_counts(dropna=False)

churn
No     11466
Yes     3534
Name: count, dtype: int64

In [40]:
transactions["payment_method"].value_counts(dropna=False)

payment_method
UPI            20104
Net Banking    20045
Wallet         19946
Card           19905
Name: count, dtype: int64

In [41]:
transactions["payment_status"].value_counts(dropna=False)

payment_status
Paid      65691
Late       9501
Failed     4808
Name: count, dtype: int64

In [42]:
support_tickets["issue_type"].value_counts(dropna=False)

issue_type
Billing      3404
Refund       3356
Technical    3352
Speed        3336
Login        3305
Network      3247
Name: count, dtype: int64

In [43]:
support_tickets["priority"].value_counts(dropna=False)

priority
Medium    6764
High      6648
Low       6588
Name: count, dtype: int64

## CHECK NUMERICAL OUTLIERS

In [44]:
customers[["age","tenure_months"]].describe()

                age  tenure_months
count  15000.000000   15000.000000
mean      43.434133      30.431867
std       15.057542      17.206720
min       18.000000       1.000000
25%       31.000000      16.000000
50%       43.000000      30.000000
75%       57.000000      45.000000
max       69.000000      60.000000

In [53]:
customer_usage[[
    "data_usage_gb",
    "call_minutes",
    "sms_count"
]].describe()

       data_usage_gb  call_minutes     sms_count
count   45000.000000  45000.000000  45000.000000
mean      251.475980   2009.022644    249.115378
std       143.903597   1148.569007    144.354629
min         1.010000     20.000000      0.000000
25%       126.362500   1018.000000    125.000000
50%       252.920000   2007.000000    249.000000
75%       375.360000   3009.000000    374.000000
max       499.990000   3999.000000    499.000000

In [52]:
support_tickets[["resolution_days","satisfaction_score"]].describe()

       resolution_days  satisfaction_score
count     20000.000000        20000.000000
mean         10.452100            2.994750
std           5.752631            1.407736
min           1.000000            1.000000
25%           5.000000            2.000000
50%          10.000000            3.000000
75%          15.000000            4.000000
max          20.000000            5.000000

## Data Cleaning Summary

### Customers
- Checked duplicate records.
- Checked duplicate customer IDs.
- Analyzed missing values.
- Converted join_date to datetime.
- Checked categorical values.
- Reviewed numerical columns for potential outliers.

### Plans
- Checked duplicate records and plan IDs.
- Verified plan names and monthly fees.

### Transactions
- Checked duplicate transaction IDs.
- Converted payment_date to datetime.
- Checked payment methods and payment statuses.
- Reviewed transaction amounts.

### Customer Usage
- Checked duplicate usage IDs.
- Converted month to datetime.
- Reviewed data usage, call minutes, and SMS counts.

### Support Tickets
- Checked duplicate ticket IDs.
- Reviewed issue types and priorities.
- Checked resolution time and satisfaction scores.

### Next Step
The cleaned tables will be prepared for integration in the next stage.